name: Terraform CI Pipeline

on:
  pull_request:
  push:
    branches:
       [ main, develop*, feature/* ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: tflint --recursive

  discover-tests:
    runs-on: ubuntu-latest
    outputs:
      test_dirs: ${{ steps.set_dirs.outputs.test_dirs }}
    steps:
      - uses: actions/checkout@v4

      - id: set_dirs
        run: |
          dirs=$(ls -d tests/*/ | jq -R . | jq -s .)
          echo "test_dirs=$dirs" >> $GITHUB_OUTPUT

  test-modules:
    needs: discover-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testdir: ${{ fromJson(needs.discover-tests.outputs.test_dirs) }}
    name: Test module ${{ matrix.testdir }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ matrix.testdir }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ matrix.testdir }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ matrix.testdir }}
        run: terraform plan -out=tfplan.binary